from . import alumno
from . import reportes_diarios
from . import empresas
from . import curso
from . import anio_cursado
from . import supervisor
from . import contrato
from . import localidad
from . import provincia